gitignore = "~/dotfiles/.gitignore"

[[entries]]
from = "~/dotfiles/ssh"
to = "~/.ssh"
encrypt = true

[[entries]]
from = "~/dotfiles/bash"
to = "~"

[[entries]]
from = "~/dotfiles/env-files/.pam_environment"
to = "~/.pam_environment"
platforms = ["linux"]

[[entries]]
from = "~/dotfiles/vscodium"
to = "~"
platforms = ["linux"]

[[entries]]
from = "~/dotfiles/p10k"
to = "~"

[[entries]]
from = "~/dotfiles/pip"
to = "~/.config/pip"

[[entries]]
from = "~/dotfiles/cargo/.cargo/config"
to = "~/.cargo/config"

[[entries]]
from = "~/dotfiles/local-bin/.local/bin"
to = "~/.local/bin"

[[entries]]
from = "~/dotfiles/zsh"
to = "~"

[[entries]]
from = "~/dotfiles/omz-plugins"
to = "~/.oh-my-zsh/custom/plugins"

[[entries]]
from = "~/dotfiles/deepin-terminal-gtk"
to = "~"
platforms = ["linux"]

[[entries]]
from = "~/dotfiles/gitconfig"
to = "~"

[[entries]]
from = "~/dotfiles/electron"
to = "~"

[[entries]]
from = "~/dotfiles/fcitx5"
to = "~"
platforms = ["linux"]

[[entries]]
from = "~/dotfiles/neofetch"
to = "~"

[[entries]]
from = "~/dotfiles/Code-darwin/Library/Application Support/Code/User"
to = "~/Library/Application Support/Code/User"
platforms = ["darwin"]

[[entries]]
from = "~/dotfiles/Code-darwin/Library/Application Support/Cursor/User"
to = "~/Library/Application Support/Cursor/User"
platforms = ["darwin"]

[[entries]]
from = "~/dotfiles/rclone"
to = "~/.config/rclone"
platforms = ["linux"]
encrypt = true

[[entries]]
from = "~/dotfiles/dot_profile"
to = "~/.profile"
platforms = ["linux"]

[[entries]]
from = "~/dotfiles/dockerfiles"
to = "~/.dockerfiles"

[[entries]]
from = "~/dotfiles/htop"
to = "~"
platforms = ["linux", "darwin"]

[[entries]]
from = "~/dotfiles/kitty"
to = "~/.config/kitty"
platforms = ["linux", "darwin"]

[[entries]]
from = "~/dotfiles/wezterm"
to = "~/.config/wezterm"
platforms = ["linux", "darwin"]

[[entries]]
from = "~/dotfiles/ranger"
to = "~/.config/ranger"
platforms = ["linux", "darwin"]

[[entries]]
from = "~/dotfiles/launchctl/local.fengkx.colima.plist"
to = "~/Library/LaunchAgents/local.fengkx.colima.plist"
platforms = ["darwin"]

#[[entries]]
#from = "~/dotfiles/RimeSync/mac/custom_phrase.txt"
#to = "/tmp/_a"
#encrypt = true

[[entries]]
from = "~/dotfiles/yabai"
to = "~/.config/yabai" 
platforms = ["darwin"]

[[entries]]
from = "~/dotfiles/skhd"
to = "~/.config/skhd" 
platforms = ["darwin"]

[[entries]]
from = "~/dotfiles/sketchybar"
to = "~/.config/sketchybar" 
platforms = ["darwin"]

[[entries]]
from = "~/dotfiles/fast-syntax-highlight"
to = "~/.config/f-sy-h"
platforms = ["darwin", "linux"]


[[entries]]
from = "~/dotfiles/claude-code/models"
to = "~/.claude-code/models"
platforms = ["darwin", "linux"]
encrypt = true
